# Generated by Django 5.0.2 on 2024-04-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologypackage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='pathologypackage',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pathology'),
        ),
        migrations.AddField(
            model_name='pathologypackage',
            name='tests',
            field=models.ManyToManyField(to='api.pathologypackagetest'),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='pathology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pathology'),
        ),
        migrations.AddField(
            model_name='pathologytest',
            name='pathology_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_pathology_list', to='user.pathology'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tests',
            field=models.ManyToManyField(to='api.pathologytest'),
        ),
    ]
