# Generated by Django 5.0.2 on 2024-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='https://cpworldgroup.com/wp-content/uploads/2021/01/placeholder.png', upload_to='categories/'),
        ),
    ]
