# Generated by Django 5.0.2 on 2024-03-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologytest',
            name='regular_price',
            field=models.IntegerField(default=0),
        ),
    ]
