# Generated by Django 5.0.2 on 2024-04-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_slot_time_slot_order_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.slot'),
        ),
    ]
