# Generated by Django 5.0.2 on 2024-04-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologypackage',
            name='tests',
            field=models.ManyToManyField(to='api.pathologytest'),
        ),
    ]
