# Generated by Django 5.0.2 on 2024-04-03 03:16

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pathologypackage_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologytest',
            name='in_cart',
            field=api.models.InCartField(default=False),
        ),
    ]
