# Generated by Django 5.0.2 on 2024-04-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pathologytest_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologytest',
            name='in_cart',
        ),
    ]
