# Generated by Django 4.2.3 on 2024-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_pathologytest_in_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyPackageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pathologypackage',
            name='tests',
            field=models.ManyToManyField(to='api.pathologypackagetest'),
        ),
    ]
