# Generated by Django 4.2.3 on 2024-04-20 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_pathologytest_age_pathologytest_fasting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.FileField(upload_to='prescription/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('tests', models.ManyToManyField(blank=True, to='api.pathologytest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
