# Generated by Django 5.0.2 on 2024-04-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_prescription_user'),
        ('user', '0006_alter_pathology_not_working_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologytest',
            name='pathology_list',
            field=models.ManyToManyField(blank=True, related_name='test_pathology_list', to='user.pathology'),
        ),
    ]
