# Generated by Django 5.0.2 on 2024-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_prescription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologypackage',
            name='tests',
        ),
        migrations.AddField(
            model_name='cart',
            name='packages',
            field=models.ManyToManyField(blank=True, to='api.pathologypackage'),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(blank=True, to='api.pathologypackage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('uploaded', 'uploaded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.ImageField(upload_to='prescription/'),
        ),
        migrations.DeleteModel(
            name='PathologyPackageTest',
        ),
    ]
