# Generated by Django 5.0.2 on 2024-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='packages',
            field=models.ManyToManyField(blank=True, to='api.pathologypackage'),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(blank=True, to='api.pathologypackage'),
        ),
    ]
