# Generated by Django 5.0.2 on 2024-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cart_packages_order_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.ImageField(upload_to='prescription/'),
        ),
    ]
