# Generated by Django 5.0.2 on 2024-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_pathologypackage_tests_cart_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologypackage',
            name='tests',
            field=models.ManyToManyField(related_name='packages_tests_list', to='api.pathologytest'),
        ),
    ]
