# Generated by Django 5.0.2 on 2024-04-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pathologypackage_tests'),
        ('user', '0007_alter_pathology_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
