# Generated by Django 5.0.2 on 2024-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_is_offline_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
