# Generated by Django 5.0.2 on 2024-04-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologypackage',
            name='age',
            field=models.CharField(default='Age: 5-99 yrs', max_length=50),
        ),
        migrations.AddField(
            model_name='pathologypackage',
            name='fasting',
            field=models.CharField(default='No fasting required', max_length=50),
        ),
        migrations.AddField(
            model_name='pathologypackage',
            name='gender',
            field=models.CharField(default='For Male, Female', max_length=50),
        ),
        migrations.AddField(
            model_name='pathologypackage',
            name='report_time',
            field=models.CharField(default='Reports with in 24 hrs', max_length=50),
        ),
    ]
