# Generated by Django 5.0.2 on 2024-03-04 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathology",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
