# Generated by Django 5.0.2 on 2024-03-05 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathology", "0002_pathology_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathology",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pathology",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pathology",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pathology",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
