# Generated by Django 5.0.2 on 2024-03-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='price',
        ),
    ]
