# Generated by Django 5.0.2 on 2024-04-03 02:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_pathology_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='working_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 1, 2, 3, 4, 5, 6], size=7),
        ),
    ]
