# Generated by Django 5.0.2 on 2024-04-11 04:39

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_created_by_patient_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='not_working_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), default=[datetime.datetime(2024, 4, 11, 4, 39, 39, 455844)], size=None),
        ),
    ]
