# Generated by Django 5.0.2 on 2024-04-03 02:38

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_pathology_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='not_working_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), default=[datetime.datetime(2024, 4, 3, 2, 38, 13, 256294)], size=None),
        ),
    ]
