# Generated by Django 5.0.2 on 2024-04-20 04:00

import django.contrib.postgres.fields
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_pathology_not_working_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='working_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=user.models.Pathology.default_working_days, size=7),
        ),
    ]
