# Generated by Django 5.0.2 on 2024-04-10 17:27

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_patient_user_patient_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='not_working_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True), default=[datetime.datetime(2024, 4, 10, 17, 27, 53, 519283)], size=None),
        ),
    ]
